package main

import (
	"encoding/json"
	"net/http"
)

type listado struct {
	titulo   string
	cantidad int
}

type AutoGenerated []struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

func main() {

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		items := listado{"Cursos Go", 30}
		json.NewEncoder(w).Encode(items)
	})

	http.ListenAndServe(":8000", nil)
}
